### ISSUE TITLE
 The size of tensor a (10) must match the size of tensor b (11) at non-singleton dimension 

### ISSUE THREAD

**Issue by young-chao** [alibaba/FederatedScope#364]
```
# For server
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_server.yaml

# For clients
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_client_1.yaml

python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_client_2.yaml

python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_femnist_client_3.yaml
```

I run the above corresponding codes on the terminals of the four containers respectively. When the mode is synchronous, it runs normally, and when the mode is asynchronous, it reports following errors:

2022-09-06 15:19:54,209 (server:786)INFO: ----------- Starting training (Round #0) -------------
Traceback (most recent call last):
  File "/workspace/workfile/FederatedScope/federatedscope/main.py", line 62, in <module>
    _ = runner.run()
  File "/workspace/workfile/FederatedScope/federatedscope/core/fed_runner.py", line 207, in run
    self.server.run()
  File "/workspace/workfile/FederatedScope/federatedscope/core/workers/server.py", line 247, in run
    move_on_flag = self.msg_handlers[msg.msg_type](msg)
  File "/workspace/workfile/FederatedScope/federatedscope/core/workers/server.py", line 909, in callback_funcs_model_para
    move_on_flag = self.check_and_move_on()
  File "/workspace/workfile/FederatedScope/federatedscope/core/workers/server.py", line 316, in check_and_move_on
    aggregated_num = self._perform_federated_aggregation()
  File "/workspace/workfile/FederatedScope/federatedscope/core/workers/server.py", line 455, in _perform_federated_aggregation
    result = aggregator.aggregate(agg_info)
  File "/workspace/workfile/FederatedScope/federatedscope/core/aggregators/asyn_clients_avg_aggregator.py", line 28, in aggregate
    avg_model = self._para_weighted_avg(models,
  File "/workspace/workfile/FederatedScope/federatedscope/core/aggregators/asyn_clients_avg_aggregator.py", line 77, in _para_weighted_avg
    avg_model[key] += local_model[key] * weight
RuntimeError: The size of tensor a (10) must match the size of tensor b (11) at non-singleton dimension

**Comment by xieyxclack** [comment]
The support for applying asynchronous training strategies in distributed mode is still in development (and will be coming soon!). Maybe you can choose to run with standalone mode or apply synchronous training strategies. Thanks a lot for your interest :)

**Comment by young-chao** [comment]
Thanks for your reply. I found that most of the examples in the current framework are stand-alone, and when I change the example of fgl to mode:distributed it will also report errors, is it also in development?

**Comment by rayrayraykk** [comment]
> Thanks for your reply. I found that most of the examples in the current framework are stand-alone, and when I change the example of fgl to mode:distributed it will also report errors, is it also in development?

Hello there, can you please provide your scripts or run command.

I test fgl in distributed mode, and everything works fine.
Here is an example:
server.yaml
```yaml
use_gpu: True
device: 0
early_stop:
  patience: 100
  improve_indicator_mode: mean
federate:
  mode: distributed
  make_global_eval: True
  client_num: 2
  total_round_num: 400
distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  role: 'server'
  data_idx: 1
data:
  root: data/
  type: cora
  splitter: 'louvain'
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
  task: node
train:
  local_update_steps: 4
  optimizer:
    lr: 0.25
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  metrics: ['acc', 'correct']
```
client1.yaml
```yaml
use_gpu: True
device: 0
early_stop:
  patience: 100
  improve_indicator_mode: mean
federate:
  mode: distributed
  make_global_eval: True
  client_num: 2
  total_round_num: 400
distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  client_host: '127.0.0.1'
  client_port: 50052
  role: 'client'
  data_idx: 1
data:
  root: data/
  type: cora
  splitter: 'louvain'
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
  task: node
train:
  local_update_steps: 4
  optimizer:
    lr: 0.25
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  metrics: ['acc', 'correct']
```

client2.yaml
```yaml
use_gpu: True
device: 0
early_stop:
  patience: 100
  improve_indicator_mode: mean
federate:
  mode: distributed
  make_global_eval: True
  client_num: 2
  total_round_num: 400
distribute:
  use: True
  server_host: '127.0.0.1'
  server_port: 50051
  client_host: '127.0.0.1'
  client_port: 50053
  role: 'client'
  data_idx: 2
data:
  root: data/
  type: cora
  splitter: 'louvain'
  batch_size: 1
model:
  type: gcn
  hidden: 64
  dropout: 0.5
  out_channels: 7
  task: node
train:
  local_update_steps: 4
  optimizer:
    lr: 0.25
    weight_decay: 0.0005
    type: SGD
criterion:
  type: CrossEntropyLoss
trainer:
  type: nodefullbatch_trainer
eval:
  metrics: ['acc', 'correct']

```

How to run:
```bash
 python federatedscope/main.py --cfg server.yaml
 python federatedscope/main.py --cfg client1.yaml
 python federatedscope/main.py --cfg client2.yaml
```
